/**
 * Client-side library import — fetches files from /library/ static assets.
 * Uses library/index.json (auto-generated by scripts/build-library-index.js)
 * to resolve file paths without per-directory manifests.
 */

const BASE = '/library'

let _index: string[] | null = null

/** Load the library file index (cached after first call) */
async function getIndex(): Promise<string[]> {
  if (_index) return _index
  try {
    const res = await fetch(`${BASE}/index.json`)
    if (!res.ok) return []
    const data = await res.json()
    _index = data.files ?? []
    return _index!
  } catch { return [] }
}

async function fetchText(path: string): Promise<string | null> {
  try {
    const res = await fetch(`${BASE}/${path}`)
    if (!res.ok) return null
    return await res.text()
  } catch { return null }
}

/** Extract resource refs like {{capabilities/read-code}} from content */
function extractRefs(content: string): { category: string; name: string }[] {
  const refs: { category: string; name: string }[] = []
  const seen = new Set<string>()
  const re = /\{\{([^}]+)\}\}/g
  let m
  while ((m = re.exec(content)) !== null) {
    let inner = m[1].trim()
    if (inner.startsWith('->')) inner = inner.slice(2).trim()
    else if (inner.startsWith('<<')) continue
    const parts = inner.includes('|') ? inner.split('|') : [inner]
    for (const part of parts) {
      const trimmed = part.trim()
      if (!trimmed.includes('/')) continue
      const [category, name] = trimmed.split('/', 2)
      if (category === 'nodes' || category === 'output') continue
      const cleanName = name.split('|')[0].trim()
      const key = `${category}/${cleanName}`
      if (!seen.has(key)) { seen.add(key); refs.push({ category, name: cleanName }) }
    }
  }
  return refs
}

/** Import a workflow — fetches all workflow files + referenced resources */
export async function importWorkflow(name: string): Promise<{ files: { path: string; content: string }[] }> {
  const index = await getIndex()
  const prefix = `workflows/${name}/`
  const wfPaths = index.filter(p => p.startsWith(prefix))
  if (wfPaths.length === 0) return { files: [] }

  const files: { path: string; content: string }[] = []
  const allRefs = new Set<string>()

  await Promise.all(wfPaths.map(async (fp) => {
    const content = await fetchText(fp)
    if (content) {
      // Strip "workflows/" prefix — workspace path is just "build-feature/AGENTS.md"
      const wsPath = fp.slice('workflows/'.length)
      files.push({ path: wsPath, content })
      for (const ref of extractRefs(content)) allRefs.add(`${ref.category}/${ref.name}`)
    }
  }))

  // Fetch referenced resources
  await Promise.all(Array.from(allRefs).map(async (refKey) => {
    const [category, refName] = refKey.split('/', 2)
    if (category === 'workflows') return // don't recursively import sub-workflows
    const imported = await importResource(category.replace(/s$/, ''), refName)
    for (const f of imported.files) {
      if (!files.some(existing => existing.path === f.path)) files.push(f)
    }
  }))

  return { files }
}

/** Import a single resource (handles both single-file and directory-based) */
export async function importResource(type: string, name: string): Promise<{ files: { path: string; content: string }[] }> {
  const dir = type.endsWith('s') ? type : type + 's'
  const index = await getIndex()

  // Directory-based (skills) — find all files under dir/name/
  const dirPrefix = `${dir}/${name}/`
  const dirFiles = index.filter(p => p.startsWith(dirPrefix))
  if (dirFiles.length > 0) {
    const files: { path: string; content: string }[] = []
    await Promise.all(dirFiles.map(async (fp) => {
      const content = await fetchText(fp)
      if (content) files.push({ path: fp, content })
    }))
    return { files }
  }

  // Single-file
  const content = await fetchText(`${dir}/${name}.md`) || await fetchText(`${dir}/${name}.json`)
  if (!content) return { files: [] }
  const ext = content.trimStart().startsWith('{') ? '.json' : '.md'
  return { files: [{ path: `${dir}/${name}${ext}`, content }] }
}
